/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BillPaymentRouteImport } from './routes/bill-payment'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedCardsIndexRouteImport } from './routes/_authenticated/cards/index'
import { Route as AuthenticatedBenefitsIndexRouteImport } from './routes/_authenticated/benefits/index'
import { Route as AuthenticatedServicesBankTransferRouteImport } from './routes/_authenticated/services/bank-transfer'
import { Route as AuthenticatedServicesBalanceTransferRouteImport } from './routes/_authenticated/services/balance-transfer'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BillPaymentRoute = BillPaymentRouteImport.update({
  id: '/bill-payment',
  path: '/bill-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCardsIndexRoute = AuthenticatedCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBenefitsIndexRoute =
  AuthenticatedBenefitsIndexRouteImport.update({
    id: '/benefits/',
    path: '/benefits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesBankTransferRoute =
  AuthenticatedServicesBankTransferRouteImport.update({
    id: '/services/bank-transfer',
    path: '/services/bank-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesBalanceTransferRoute =
  AuthenticatedServicesBalanceTransferRouteImport.update({
    id: '/services/balance-transfer',
    path: '/services/balance-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/bill-payment': typeof BillPaymentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/services/balance-transfer': typeof AuthenticatedServicesBalanceTransferRoute
  '/services/bank-transfer': typeof AuthenticatedServicesBankTransferRoute
  '/benefits': typeof AuthenticatedBenefitsIndexRoute
  '/cards': typeof AuthenticatedCardsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesByTo {
  '/bill-payment': typeof BillPaymentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/services/balance-transfer': typeof AuthenticatedServicesBalanceTransferRoute
  '/services/bank-transfer': typeof AuthenticatedServicesBankTransferRoute
  '/benefits': typeof AuthenticatedBenefitsIndexRoute
  '/cards': typeof AuthenticatedCardsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/bill-payment': typeof BillPaymentRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/services/balance-transfer': typeof AuthenticatedServicesBalanceTransferRoute
  '/_authenticated/services/bank-transfer': typeof AuthenticatedServicesBankTransferRoute
  '/_authenticated/benefits/': typeof AuthenticatedBenefitsIndexRoute
  '/_authenticated/cards/': typeof AuthenticatedCardsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/bill-payment'
    | '/login'
    | '/signup'
    | '/'
    | '/services/balance-transfer'
    | '/services/bank-transfer'
    | '/benefits'
    | '/cards'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bill-payment'
    | '/login'
    | '/signup'
    | '/'
    | '/services/balance-transfer'
    | '/services/bank-transfer'
    | '/benefits'
    | '/cards'
    | '/services'
  id:
    | '__root__'
    | '/_authenticated'
    | '/bill-payment'
    | '/login'
    | '/signup'
    | '/_authenticated/'
    | '/_authenticated/services/balance-transfer'
    | '/_authenticated/services/bank-transfer'
    | '/_authenticated/benefits/'
    | '/_authenticated/cards/'
    | '/_authenticated/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BillPaymentRoute: typeof BillPaymentRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-payment': {
      id: '/bill-payment'
      path: '/bill-payment'
      fullPath: '/bill-payment'
      preLoaderRoute: typeof BillPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cards/': {
      id: '/_authenticated/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benefits/': {
      id: '/_authenticated/benefits/'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/bank-transfer': {
      id: '/_authenticated/services/bank-transfer'
      path: '/services/bank-transfer'
      fullPath: '/services/bank-transfer'
      preLoaderRoute: typeof AuthenticatedServicesBankTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/balance-transfer': {
      id: '/_authenticated/services/balance-transfer'
      path: '/services/balance-transfer'
      fullPath: '/services/balance-transfer'
      preLoaderRoute: typeof AuthenticatedServicesBalanceTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedServicesBalanceTransferRoute: typeof AuthenticatedServicesBalanceTransferRoute
  AuthenticatedServicesBankTransferRoute: typeof AuthenticatedServicesBankTransferRoute
  AuthenticatedBenefitsIndexRoute: typeof AuthenticatedBenefitsIndexRoute
  AuthenticatedCardsIndexRoute: typeof AuthenticatedCardsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedServicesBalanceTransferRoute:
    AuthenticatedServicesBalanceTransferRoute,
  AuthenticatedServicesBankTransferRoute:
    AuthenticatedServicesBankTransferRoute,
  AuthenticatedBenefitsIndexRoute: AuthenticatedBenefitsIndexRoute,
  AuthenticatedCardsIndexRoute: AuthenticatedCardsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BillPaymentRoute: BillPaymentRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
